[package]
name = "calr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
itertools = "0.12"
ansi_term = "0.12"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
